### ISSUE TITLE
Firefox marked this add-on as legacy

### ISSUE THREAD

**Issue by silpol** [PowerClose/power-close#13]
Currently my Firefox 56 on Ubuntu shows this add-on as Legacy yellow labeled, for that Mozilla has [page which explains](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u) why they do so, what is going on, where it goes and what to do about it.

BTW, release 57 should be soon.

**Comment by mos3abof** [comment]
@silpol, thank you for bringing this to my attention. I will free some time this weekend to work on this.

**Comment by mina-asham** [comment]
@mos3abof Firefox moved to the Chrome extension API, theoretically the same extension for Chrome should now work with Firefox, needs testing and re-releasing. Happy to help since I wrote that fork if needed.

**Comment by mos3abof** [comment]
@mina-asham, your input is always valuable. :)

I will port your fork over the weekend.

**Comment by ChristopherSchultz** [comment]
Any update on this? I haven't been able to find anything like power-closer for the current version(s) of Firefox, and I have a *serious* tab addiction that can only be helped with this great add-on. @mina-asham, where can I find your Chrome add-on to try with Firefox, and if it works, is it likely that this (older) version will be abandoned @mos3abof?

Thanks for the simple and powerful add-on. I made great use of it in the past.

**Comment by mina-asham** [comment]
@ChristopherSchultz It's available on a branch here: https://github.com/mos3abof/power-close/tree/feature/web-extensions, worth mentioning I haven't updated it since then, so I wouldn't say it's maintained much, but the platform shouldn't have changed since then.

**Comment by mos3abof** [comment]
@silpol, and @ChristopherSchultz, the extension has been updated, and published to Firefox's extensions.
